_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: -43
  standard__front_page:
    weight: -38
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
