_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  layout_builder: 0
  layout_custom_section_classes: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  nextpre: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  path: 0
  path_alias: 0
  rdf: 0
  search: 0
  shortcut: 0
  standard: 0
  statistics: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  views: 10
  paragraphs: 11
theme:
  bartik: 0
  seven: 0
  olivero: 0
  bootstrap: 0
  mytheme: 0
  stable: 0
  classy: 0
  bootstrap5: 0
  b5subtheme: 0
profile: standard
