url: 'https://bank.gov.ua/NBU_Exchange/exchange_site'
request: 1
currency:
  AUD: AUD
  MDL: MDL
  AMD: 0
  CAD: 0
  CNY: 0
  CZK: 0
  DKK: 0
  HKD: 0
  HUF: 0
  INR: 0
  IDR: 0
  IRR: 0
  IQD: 0
  ILS: 0
  JPY: 0
  KZT: 0
  KRW: 0
  KGS: 0
  LBP: 0
  LYD: 0
  MYR: 0
  MXN: 0
  MAD: 0
  NZD: 0
  NOK: 0
  PKR: 0
  RUB: 0
  SGD: 0
  VND: 0
  ZAR: 0
  SEK: 0
  CHF: 0
  THB: 0
  AED: 0
  TND: 0
  EGP: 0
  GBP: 0
  USD: 0
  UZS: 0
  BYN: 0
  TMT: 0
  RSD: 0
  RON: 0
  TRY: 0
  TJS: 0
  BGN: 0
  GEL: 0
  PLN: 0
  BRL: 0
  DOP: 0
  XAU: 0
  XDR: 0
  XAG: 0
  XPT: 0
  XPD: 0
  EUR: 0
  AZN: 0
  SAR: 0
  TWD: 0
  DZD: 0
  BDT: 0
range: '3'
