_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 65d498df-bf2a-4822-a25b-60a1a7bb85d4
name: Site
mail: site@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /newspaper_life_news
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
