name: Drupal coding standards

on: [pull_request]

jobs:
  phpcs-drupal:
    name: Drupal coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guix77/phpcs-drupal-action@v1.0.1
        with:
          memory_limit: 512M
